/*
 * build-locales.js — generate client/locale/locales.js from the JSON sources.
 *
 * CEP panels run from file://, where fetch()/XHR of local JSON is unreliable.
 * The bulletproof path is to load locales as a plain <script> that assigns a
 * global — zero I/O. ar.json / en.json stay the single source of truth (tests
 * read them); this bundles them into locales.js. A test asserts the bundle is
 * in sync, so drift is caught in CI.
 *
 * Run: node tools/build-locales.js
 */
'use strict';

var fs = require('fs');
var path = require('path');

var localeDir = path.join(__dirname, '..', 'client', 'locale');
var ar = JSON.parse(fs.readFileSync(path.join(localeDir, 'ar.json'), 'utf8'));
var en = JSON.parse(fs.readFileSync(path.join(localeDir, 'en.json'), 'utf8'));

var banner =
  '/* AUTO-GENERATED by tools/build-locales.js — do not edit by hand.\n' +
  '   Edit ar.json / en.json then run: node tools/build-locales.js */\n';

var body =
  'window.IMPLocales = {\n' +
  '  ar: ' + JSON.stringify(ar, null, 2) + ',\n' +
  '  en: ' + JSON.stringify(en, null, 2) + '\n' +
  '};\n';

var out = banner + body;
var outPath = path.join(localeDir, 'locales.js');

// Export the expected content for the sync test; write when run directly.
module.exports = { expected: out, outPath: outPath };

if (require.main === module) {
  fs.writeFileSync(outPath, out, 'utf8');
  console.log('wrote ' + path.relative(path.join(__dirname, '..'), outPath));
}
